// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg9ZvT3haD97oEA5QtqDOeFFecGx4-5WE',
    appId: '1:918880027506:web:1f31c3048512b535d493eb',
    messagingSenderId: '918880027506',
    projectId: 'beatsync-prod',
    authDomain: 'beatsync-prod.firebaseapp.com',
    storageBucket: 'beatsync-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnOe4yUBANnHFTlCa40LOjt2RTAhlGz5Q',
    appId: '1:918880027506:android:8059140f2cf1b746d493eb',
    messagingSenderId: '918880027506',
    projectId: 'beatsync-prod',
    storageBucket: 'beatsync-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCInuQ2CfJ96RoxHyjH8O0-He7tcb5isbI',
    appId: '1:918880027506:ios:1ed192afefbeabdad493eb',
    messagingSenderId: '918880027506',
    projectId: 'beatsync-prod',
    storageBucket: 'beatsync-prod.firebasestorage.app',
    iosBundleId: 'com.beatsync.beatsync',
  );
}
